// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/category-model.dart';
import 'models/transaction-model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2050938176515586413),
    name: 'TransactionModel',
    lastPropertyId: const obx_int.IdUid(8, 8312084202800016938),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2895756432895543091),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7245032256904451746),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7883175945406580159),
        name: 'categoryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 131005187125686936),
        name: 'categoryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9191167316294712495),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6694972689959416705),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8312084202800016938),
        name: 'isIncome',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7823711188347547548),
    name: 'CategoryModel',
    lastPropertyId: const obx_int.IdUid(4, 7384189003144841753),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3834696292565548154),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7214137678686633907),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3729159571809626746),
        name: 'iconCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7384189003144841753),
        name: 'isIncome',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7823711188347547548),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [2858780137494542985],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TransactionModel: obx_int.EntityDefinition<TransactionModel>(
      model: _entities[0],
      toOneRelations: (TransactionModel object) => [],
      toManyRelations: (TransactionModel object) => {},
      getId: (TransactionModel object) => object.id,
      setId: (TransactionModel object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionModel object, fb.Builder fbb) {
        final categoryNameOffset = fbb.writeString(object.categoryName);
        final noteOffset = fbb.writeString(object.note);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, categoryNameOffset);
        fbb.addInt64(4, object.categoryId);
        fbb.addOffset(5, noteOffset);
        fbb.addInt64(6, object.date.millisecondsSinceEpoch);
        fbb.addBool(7, object.isIncome);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final categoryNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isIncomeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = TransactionModel(
          amount: amountParam,
          categoryName: categoryNameParam,
          categoryId: categoryIdParam,
          note: noteParam,
          date: dateParam,
          isIncome: isIncomeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    CategoryModel: obx_int.EntityDefinition<CategoryModel>(
      model: _entities[1],
      toOneRelations: (CategoryModel object) => [],
      toManyRelations: (CategoryModel object) => {},
      getId: (CategoryModel object) => object.id,
      setId: (CategoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.iconCode);
        fbb.addBool(3, object.isIncome);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconCodeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final isIncomeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = CategoryModel(
          name: nameParam,
          iconCode: iconCodeParam,
          isIncome: isIncomeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TransactionModel] entity fields to define ObjectBox queries.
class TransactionModel_ {
  /// See [TransactionModel.id].
  static final id = obx.QueryIntegerProperty<TransactionModel>(
    _entities[0].properties[0],
  );

  /// See [TransactionModel.amount].
  static final amount = obx.QueryDoubleProperty<TransactionModel>(
    _entities[0].properties[1],
  );

  /// See [TransactionModel.categoryName].
  static final categoryName = obx.QueryStringProperty<TransactionModel>(
    _entities[0].properties[2],
  );

  /// See [TransactionModel.categoryId].
  static final categoryId = obx.QueryIntegerProperty<TransactionModel>(
    _entities[0].properties[3],
  );

  /// See [TransactionModel.note].
  static final note = obx.QueryStringProperty<TransactionModel>(
    _entities[0].properties[4],
  );

  /// See [TransactionModel.date].
  static final date = obx.QueryDateProperty<TransactionModel>(
    _entities[0].properties[5],
  );

  /// See [TransactionModel.isIncome].
  static final isIncome = obx.QueryBooleanProperty<TransactionModel>(
    _entities[0].properties[6],
  );
}

/// [CategoryModel] entity fields to define ObjectBox queries.
class CategoryModel_ {
  /// See [CategoryModel.id].
  static final id = obx.QueryIntegerProperty<CategoryModel>(
    _entities[1].properties[0],
  );

  /// See [CategoryModel.name].
  static final name = obx.QueryStringProperty<CategoryModel>(
    _entities[1].properties[1],
  );

  /// See [CategoryModel.iconCode].
  static final iconCode = obx.QueryIntegerProperty<CategoryModel>(
    _entities[1].properties[2],
  );

  /// See [CategoryModel.isIncome].
  static final isIncome = obx.QueryBooleanProperty<CategoryModel>(
    _entities[1].properties[3],
  );
}
